### ISSUE TITLE
UI representation of OH items todo

### ISSUE THREAD

**Issue by simonpoole** [simonpoole/OpeningHoursFragment#5]
Tick off when basic implementation exists (value is displayed and modifications are reflected back to the OH value):

- [x] rule type (replace, fallback)
- [x] year ranges
- [x] year ranges interval
- [x] rule modifiers with comments
- [x] comments
- [x] date ranges
- [x] date range open end
- date ranges interval ---- likely an error in the OH specification
- [x] date day offsets
- [x] date weekday offsets
- [x] variable-date - date
- [x] date - variable-date
- [x] variable-date - variable-date
- [x] variable-dates offsets
- [x] week ranges
- [x] week ranges intervals
- [x] weekday ranges
- [x] weekday nth
- [x] weekday offsets
- [x] holidays
- [x] holiday offsets
- [x] 24/7
- [x] normal time range
- [x] point in time
- [x] time - variable-time time range
- [x] time range open ended
- [x] extended time range
- [x] variable-time  - variable-time  time range
- [x] variable-time  - time time range
- [x] variable-time - extended time range
- [x] interval for time range
- [x] variable-time  offsets

**Comment by simonpoole** [comment]
Basic editing exists for all elements.
